# Generated by Django 4.2.4 on 2024-04-01 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255, null=True)),
                ('datetime', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('P', 'planned'), ('M', 'missed'), ('D', 'done'), ('C', 'canceled')], default='P', max_length=10)),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['-datetime'],
            },
        ),
    ]
