# Generated by Django 4.2.4 on 2024-04-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
    ]
