# Generated by Django 4.2.4 on 2024-04-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0002_remove_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('P', 'Запланировано'), ('M', 'Пропущено'), ('D', 'Завершено'), ('C', 'Отменено')], default='P', verbose_name='Статус'),
        ),
    ]
