# Generated by Django 5.0.4 on 2024-06-10 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0002_alter_lesson_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(related_name='student_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
