# Generated by Django 4.2.4 on 2024-04-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0004_course_projecttype_review_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lesson_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lesson_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lesson_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lesson_4',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lesson_5',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
