# Generated by Django 4.2.4 on 2024-04-09 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_calendar', '0005_alter_project_lesson_1_alter_project_lesson_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ManyToManyField(to='event_calendar.projecttype', verbose_name='Тип'),
        ),
    ]
