# Generated by Django 4.2.4 on 2024-04-09 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_calendar', '0008_project_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
    ]
