# Generated by Django 5.0.4 on 2024-06-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, verbose_name='Название упражнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='ExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_1', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('step_2', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('step_3', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('step_4', models.SmallIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Результат упражнения',
                'verbose_name_plural': 'Результаты упражнений',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('translate', models.CharField(max_length=255)),
                ('lang', models.CharField(choices=[('eng', 'English'), ('fr', 'French'), ('sp', 'Spanish')], default='eng', max_length=10)),
                ('sentences', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Слово для изучения',
                'verbose_name_plural': 'Слова для изучения',
            },
        ),
    ]
