# Generated by Django 4.2.4 on 2024-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='sentences',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
