# Generated by Django 4.2.4 on 2024-04-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_word_sentences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseresult',
            name='step',
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='step_four',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='step_one',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='step_three',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='exerciseresult',
            name='step_two',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
