# Generated by Django 4.2.4 on 2024-04-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exerciseresult_step_exerciseresult_step_four_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseresult',
            old_name='step_four',
            new_name='step_1',
        ),
        migrations.RenameField(
            model_name='exerciseresult',
            old_name='step_one',
            new_name='step_2',
        ),
        migrations.RenameField(
            model_name='exerciseresult',
            old_name='step_three',
            new_name='step_3',
        ),
        migrations.RenameField(
            model_name='exerciseresult',
            old_name='step_two',
            new_name='step_4',
        ),
    ]
