exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "/home/peka97/Verbal-Voyager/scripts/*",
]

line-length = 88
indent-width = 4
target-version = "py39"

[lint]
# Основные правила:
# - E/W: PEP 8 (без E501, если не хотите строгой проверки длины строки)
# - F: Pyflakes (ошибки логики)
# - I: Сортировка импортов (isort)
# - B: print() и другие "запрещёнки" (B002, B010)
# - UP: Modern Python (например, Union → |)
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "T201",
    "I",
    "B",
    "UP",
    "W",
] # Добавлены I, B, UP, W

# Игнорируем слишком строгие/неудобные правила
ignore = [
    "E501", # Длина строки (если хотите включить — удалите эту строку)
    "E203", # Пробел перед ':' (конфликтует с black)
    "F403", # from ... import * (иногда нужно в Django)
    "F401", # Неиспользуемый импорт (может мешать в __init__.py)
]

# Разрешаем автофикс для всех правил
fixable = ["ALL"]
unfixable = []

# Разрешаем неиспользуемые переменные с префиксом _
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Игнорируем миграции Django и тесты для print()
[lint.per-file-ignores]
"*/migrations/*.py" = ["F401", "E402"] # Игнор для миграций
"tests/*.py" = ["B002"]                # Разрешаем print() в тестах

# Настройки isort (сортировка импортов)
[isort]
known-first-party = ["verbalvoyager"] # Замените на имя вашего Django-приложения
lines-after-imports = 2
force-sort-within-sections = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
