# Generated by Django 4.2.4 on 2024-03-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_review_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='datetime',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
