# Generated by Django 4.2.4 on 2024-04-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='from_user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
