name: Django CI/CD

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database for testing
        run: |
          # You need to configure your PostgreSQL service here.
          # This is a placeholder and needs to be adapted for your environment.
          # For example, starting the PostgreSQL service or using a container.
          #  sudo systemctl start postgresql
          echo "Database setup instructions go here!"

      - name: Run migrations
        working-directory: /home/runner/work/Verbal-Voyager/Verbal-Voyager/
        run: python manage.py migrate

      - name: Run tests with pytest
        working-directory: /home/runner/work/Verbal-Voyager/Verbal-Voyager/
        run: pytest
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test_verbal_voyager"

      - name: Lint with Ruff
        working-directory: /home/runner/work/Verbal-Voyager/Verbal-Voyager/
        run: |
          python -m pip install ruff
          ruff check .
