name: Django CI/CD

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database for testing
        run: |
          # You need to configure your PostgreSQL service here.
          # This is a placeholder and needs to be adapted for your environment.
          # For example, starting the PostgreSQL service or using a container.
          #  sudo systemctl start postgresql
          echo "Database setup instructions go here!"

      - name: Run migrations
        working-directory: ${{ github.workspace }}/verbalvoyager/
        env:
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          EMAIL_LOGIN: ${{ secrets.EMAIL_LOGIN }}
          EMAIL_PSWD: ${{ secrets.EMAIL_PSWD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PSQL_USER: ${{ secrets.PSQL_USER }}
          PSQL_PSWD: ${{ secrets.PSQL_PSWD }}
        run: python manage.py migrate

      - name: Run tests with pytest
        working-directory: ${{ github.workspace }}/verbalvoyager/
        env:
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          EMAIL_LOGIN: ${{ secrets.EMAIL_LOGIN }}
          EMAIL_PSWD: ${{ secrets.EMAIL_PSWD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PSQL_USER: ${{ secrets.PSQL_USER }}
          PSQL_PSWD: ${{ secrets.PSQL_PSWD }}
        run: pytest

      - name: Lint with Ruff
        working-directory: ${{ github.workspace }}/verbalvoyager/
        run: |
          python -m pip install ruff
          ruff check .
