name: Django CI

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:14.17
        env:
          POSTGRES_USER: ${{ secrets.PSQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PSQL_PSWD }}
          POSTGRES_DB: verbalvoyagertest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:6.0.16
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PostgreSQL
        run: |
          psql -U postgres -h localhost -c "CREATE USER ${{ secrets.DB_USER }} WITH PASSWORD ${{ secrets.DB_PASSWORD }};"
          psql -U postgres -h localhost -c "CREATE DATABASE ${{ secrets.DB_NAME }} WITH OWNER ${{ secrets.DB_USER }};"
          psql -U postgres -h localhost -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_NAME }} TO ${{ secrets.DB_USER }};"

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create logging directory
        working-directory: ${{ github.workspace }}/verbalvoyager/
        run: |
          mkdir logs
          touch logs/django.log
          touch logs/words.log

      - name: Make migrations
        working-directory: ${{ github.workspace }}/verbalvoyager/
        env:
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          INTERNAL_IPS: ${{ secrets.INTERNAL_IPS }}
          CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
          ADMIN_TOOLS_ENABLE: ${{ secrets.ADMIN_TOOLS_ENABLE }}
          SITE_NAME: ${{ secrets.SITE_NAME }}
          DB_ENGINE: ${{ secrets.DB_ENGINE }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
          REDIS_BACKEND: ${{ secrets.REDIS_BACKEND }}
          REDIS_DEFAULT_LOCATION: ${{ secrets.REDIS_DEFAULT_LOCATION }}
          REDIS_DEFAULT_PREFIX: ${{ secrets.REDIS_DEFAULT_PREFIX }}
          REDIS_SESSION_LOCATION: ${{ secrets.REDIS_SESSION_LOCATION }}
          REDIS_SESSION_PREFIX: ${{ secrets.REDIS_SESSION_PREFIX }}
          REDIS_VERSION: ${{ secrets.REDIS_VERSION }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
          RECAPTCHA_PUBLIC_KEY: ${{ secrets.RECAPTCHA_PUBLIC_KEY }}
          RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LOGGING_DJANGO_FILE_FP: ${{ secrets.LOGGING_DJANGO_FILE_FP }}
          LOGGING_WORDS_FILE_FP: ${{ secrets.LOGGING_WORDS_FILE_FP }}
          SILENCED_SYSTEM_CHECKS: django_recaptcha.recaptcha_test_key_error
        run: python manage.py makemigrations

      - name: Migrate
        working-directory: ${{ github.workspace }}/verbalvoyager/
        env:
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          INTERNAL_IPS: ${{ secrets.INTERNAL_IPS }}
          CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
          ADMIN_TOOLS_ENABLE: ${{ secrets.ADMIN_TOOLS_ENABLE }}
          SITE_NAME: ${{ secrets.SITE_NAME }}
          DB_ENGINE: ${{ secrets.DB_ENGINE }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
          REDIS_BACKEND: ${{ secrets.REDIS_BACKEND }}
          REDIS_DEFAULT_LOCATION: ${{ secrets.REDIS_DEFAULT_LOCATION }}
          REDIS_DEFAULT_PREFIX: ${{ secrets.REDIS_DEFAULT_PREFIX }}
          REDIS_SESSION_LOCATION: ${{ secrets.REDIS_SESSION_LOCATION }}
          REDIS_SESSION_PREFIX: ${{ secrets.REDIS_SESSION_PREFIX }}
          REDIS_VERSION: ${{ secrets.REDIS_VERSION }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
          RECAPTCHA_PUBLIC_KEY: ${{ secrets.RECAPTCHA_PUBLIC_KEY }}
          RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LOGGING_DJANGO_FILE_FP: ${{ secrets.LOGGING_DJANGO_FILE_FP }}
          LOGGING_WORDS_FILE_FP: ${{ secrets.LOGGING_WORDS_FILE_FP }}
          SILENCED_SYSTEM_CHECKS: django_recaptcha.recaptcha_test_key_error
        run: python manage.py migrate

      - name: Run tests
        working-directory: ${{ github.workspace }}/verbalvoyager/
        env:
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_TEST_MODULE }}
          DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          INTERNAL_IPS: ${{ secrets.INTERNAL_IPS }}
          CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
          ADMIN_TOOLS_ENABLE: ${{ secrets.ADMIN_TOOLS_ENABLE }}
          SITE_NAME: ${{ secrets.SITE_NAME }}
          DB_ENGINE: ${{ secrets.DB_ENGINE }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
          REDIS_BACKEND: ${{ secrets.REDIS_BACKEND }}
          REDIS_DEFAULT_LOCATION: ${{ secrets.REDIS_DEFAULT_LOCATION }}
          REDIS_DEFAULT_PREFIX: ${{ secrets.REDIS_DEFAULT_PREFIX }}
          REDIS_SESSION_LOCATION: ${{ secrets.REDIS_SESSION_LOCATION }}
          REDIS_SESSION_PREFIX: ${{ secrets.REDIS_SESSION_PREFIX }}
          REDIS_VERSION: ${{ secrets.REDIS_VERSION }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
          RECAPTCHA_PUBLIC_KEY: ${{ secrets.RECAPTCHA_PUBLIC_KEY }}
          RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LOGGING_DJANGO_FILE_FP: ${{ secrets.LOGGING_DJANGO_FILE_FP }}
          LOGGING_WORDS_FILE_FP: ${{ secrets.LOGGING_WORDS_FILE_FP }}
        run: pytest

      - name: Lint with Ruff
        working-directory: ${{ github.workspace }}/verbalvoyager/
        run: |
          python -m pip install ruff
          ruff check